name: mc-server-plugin
version: 3.0
author: Hanuta
main: az.main.Mainclass
commands:
  heal:
  gm:
  tc:
  bc:
  op:
  deop:
  tpa:
  tpaccept:
  tpacancel:
  tpadeny:
  difficulty:
  gamemode:
  sleep:
